version: '3.8'

services:
  saathi_tx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - .:/app  
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - DB_URL=mysql://root:inRKI@0510@49.50.119.39:3306/saathi_db_tx
    networks:
      - railkriti  # Updated network name

networks:
  railkriti:
    external: true  # This indicates that the network already exists
